apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-time-depl
  labels:
    app: movietime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movietime
  template:
    metadata:
      labels:
        app: movietime
    spec:
      containers:
      - name: movie-time
        image: disciklean/movie-time
        ports:
          - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: movie-time-srv
spec:
  selector:
    app: movietime
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
    nodePort: 30001
